### ISSUE TITLE
Configuration GUI

### ISSUE THREAD

**Issue by Minecraftschurli** [dzikoysk/reposilite#1044]
### Request details

Add a propper configuration gui instead of the current (edit the config file stored in the database) text editor

**Comment by dzikoysk** [comment]
You can still mount external configuration file through `--shared-configuration=/etc/reposilite/shared.configuration.cdn` parameter, it's just not recommended as long as you're using persistent storage.The reason why we're moving away from static file is because:
1. It's quite hard to maintain configuration in containers for users that want to stay up-to-date
2. Reposilite 3.x works pretty much like microservice, it means you can spawn multiple instances. For such usage, we need to separate instance configuration from general setup of Maven repo
3. Support for hot-reloading of properties - we don't have to restart instance to e.g. add a new repository anymore
4. Configuration gets more and more properties and it's kinda mixed with commands, in the end we'd like to provide one consistent panel, so we can move away from raw config file and CLI with commands, to simplify user experience in general
