### ISSUE TITLE
Use status code 403 (Forbidden) when a token lacks permissions

### ISSUE THREAD

**Issue by jorisguffens** [dzikoysk/reposilite#1061]
### What happened?

When access to a resource is denied because the token lacks permissions it should result in a 403 (Forbidden) instead of a 401 (Unauthorized).

Due this issue I was misinformed of the actual problem. I thought something was wrong with my credentials when in fact the credentials were correct but I forgot to give write permissions.

Further reading:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

### Reposilite version

3.x

### Relevant log output

```shell
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':commands:publishReleasePublicationToJorisgRepository'.
> Failed to publish publication 'release' to repository 'Jorisg'
   > Could not PUT 'https://repo.jorisg.com/snapshots/com/gufli/brickutils/commands/1.0-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Unauthorized
```

**Comment by dzikoysk** [comment]
Fair point, thanks for reporting this! Atm I'm kinda busy, so I'll be able to fix this next week as it's also not that urgent.

**Comment by Saladoc** [comment]
Would this leak information about the artifacts stored?
Assume Alice had read/write permissions to the `com.alice` namespace, but Bob does not. If Bob were to try and access `com.alice.secretproject`, would he get
 - 403 (indicating there was a project there that Bob couldn't see), but 404 on `com.alice.doesntexist`
 - 403 no matter what he requests on a path he has no read access to
 - 404 no matter what he requests on a path he has no read access to

Especially if tokens lack read permissions they should not get to probe for the existance of certain directories / artifacts / files. If read access is given and the action is denied due to lacking write access, a 403 is obviously the right choice.

**Comment by dzikoysk** [comment]
No, authorization is performed first, so no matter if artifact exists or not, Bob would get 403. The only difference between 401 & 403 is that the first one is thrown for anonymous/bad credentials scenarios, where the 403 is thrown for illegal access in general. It means that only Alice can get 404 in any of the specified scenarios.
