### ISSUE TITLE
Group properties in shared configuration by domain

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#1151]
### Request details

Currently, the structure of shared configuration is quite random, because it was dedicated for text-based usage. We should abandon this concept to simplify internals and avoid unnecessary conversions (#1081) between various data objects. 

Goals:
* Each domain has it's own configuration object in `application` package
* Domain configuration is just a plain class with raw properties described by `@Description` annotation
* Shared configuration links all built-in domain configurations using reactive `reference<>` to support hot-reloads

Related:
* #1081 
* #1044

**Comment by Minecraftschurli** [comment]
I would suggest to either move to a different annotation that stores data instead of a documentation string 
(like `@Doc(title="A Title", summary="A short description", description="A longer description"` where description is optional and defaults to the value of summary) or even add tis functionality upstream (in cdn) this way we can more easily generate things like the schema that the frontend consumes for the config gui

**Comment by dzikoysk** [comment]
Yeah, I was thinking about this, but I don't really see an option to support it through CDN - it's not quite related tbh. Anyway, I agree that having sth like that could be interesting, so we can generate form scheme on top of that. 

I think we could try to write small and simple annotation processor in [reposilite-playground](https://github.com/reposilite-playground) repository that generates jsonfroms scheme at build time, just like the [javalin-openapi](https://github.com/reposilite-playground/javalin-openapi) 😳
