### ISSUE TITLE
Update manifest of jar hosted by Reposilite at download time using plugin

### ISSUE THREAD

**Issue by rdehuyss** [dzikoysk/reposilite#1285]
### Request details

Using a plugin, would it be possible to update the manifest of a jar when a client downloads it?

I know it is against best practices of build once but the use case would be if users are downloading a trial / pro version of a certain jar. One could add the username and the date until the trial of the lib/jar to the manifest of that jar.

**Comment by dzikoysk** [comment]
Hi :) Yes, it should be possible with this event:

* https://github.com/dzikoysk/reposilite/blob/e1bb1de7b72682251954a3f68189f6cbbe47696c/reposilite-backend/src/main/kotlin/com/reposilite/maven/api/LookupApi.kt#L52

MavenFacade emits this event each time the given file is properly resolved. To properly use `MavenFacade`, all you need is to add a dependency on maven domain `dependencies = ["maven"]`.

**Comment by rdehuyss** [comment]
Thanks for the swift response! I'll have a look!

**Comment by rdehuyss** [comment]
Hi @dzikoysk - I was able to setup a plugin for resolving Maven Events and I have some more questions:
- the accessToken does not contain the username nor any other id or so... how would I achieve that?
- how can I intercept the MavenRequest and return my own response?

Thx for this great project!
Ronald

**Comment by dzikoysk** [comment]
Hi, access token does not have username, because in Reposilite we don't really have a concept of "user", but you can just use the name to provide some kind of meaningful identifier:

* https://github.com/dzikoysk/reposilite/blob/a179081b55d774e8460e85005b6c1300dcfec5ae/reposilite-backend/src/main/kotlin/com/reposilite/token/AccessToken.kt#L38

Speaking of the custom response, it's not currently possible. Because plugin system is quite a new feature, we're mostly focused on subscribing to events rather than full event-driven approach, because it significantly affects internals and all related logic. Why you'd like to override the response of this built-in endpoint?

**Comment by rdehuyss** [comment]
Thanks for the swift response!

- From what I saw, the event only has the `AccessTokenIdentifier` and not the `AccessToken`. I'm indeed looking for the name.
- regarding custom response: is it possible to change the repo (so where the actual jar is read from disk) when a client connects? The reason is the same as above: I would like to add the name of the `AccesToken` to the manifest of the jar that is downloaded. I know, not best practice but it would allow me to hand out trials of my jar.

**Comment by dzikoysk** [comment]
You have to add a dependency for a `access_token` domain and then you can access the `AccessTokenFacade` during initialization of your custom plugin. AccessTokenFacade exposes several functions, one of them is a method that will allow you to fetch token details:

* https://github.com/dzikoysk/reposilite/blob/a179081b55d774e8460e85005b6c1300dcfec5ae/reposilite-backend/src/main/kotlin/com/reposilite/token/AccessTokenFacade.kt#L140

Having this, you should be able to store the information about the access to the resource. I guess that because it's some kind of a trial version, you'd like to block connection at some point. As long as there is no official way to do this, in theory you could register a `before` handler in Javalin (http framework used by Reposilite) using the http init event:

* https://github.com/dzikoysk/reposilite/blob/a179081b55d774e8460e85005b6c1300dcfec5ae/reposilite-backend/src/main/kotlin/com/reposilite/web/api/HttpServerEvents.kt#L26

This is the maven endpoint path registered in Javalin, by registering the `before` handler with the same route you'd have a priority over the Reposilite's endpoint and you could e.g. throw an exception or sth like that to interrupt execution.

* https://github.com/dzikoysk/reposilite/blob/a179081b55d774e8460e85005b6c1300dcfec5ae/reposilite-backend/src/main/kotlin/com/reposilite/maven/infrastructure/MavenEndpoints.kt#L67

Anyway interesting use-case, I think we could try to improve the event api in the long run. Support for the cancellation of an event might be a good start.

**Comment by dzikoysk** [comment]
Ok, internals seems to work after the merge of latest breaking changes. I think I'll try to create PR with a proposal to solve this request based on a test case scenario. It might be an inspiration for you to write such plugin.

I was thinking about it for a while and I think it might be better to modify the resolved file instead of modifying the original file. Modifications on original file are not really thread-safe and could fail for multiple requests. I'll just add a new event that allows you to consume the resolved file (by saving to e.g. temp directory) where you can modify it and return it once again 🤔

**Comment by rdehuyss** [comment]
Perfect, that was my exact idea to only adapt the resolved file (it could perhaps even be done in memory)?

**Comment by dzikoysk** [comment]
Well, in theory you could do this in memory, but it might be not the best scenario for bigger files 🤔 The event API will require an InputStream, it doesn't really matter how you'll provide it.

**Comment by dzikoysk** [comment]
https://github.com/dzikoysk/reposilite/blob/5ca91718387d4e3210b6b107024eb0a4010261df/reposilite-backend/src/test/kotlin/com/reposilite/maven/ResolveEventTest.kt#L19-L46

What do you think about something like that? I think it reflects your needs, as I said, the event only requires a result of `Result<Pair<DocumentInfo, InputStream>, ErrorResponse>`. If you'd like to modify the JAR content, you may also need to update the checksum files, but it's up to the plugin that should be able to do it within this new event.

**Comment by rdehuyss** [comment]
I'll look into it and get back to you!

**Comment by dzikoysk** [comment]
What's the status of that? :)

**Comment by rdehuyss** [comment]
Hi @dzikoysk , I didn't get around testing this yet - I'm swamped with work currently. Let's close this for now and I'll reopen it if something doesn't work.

Either way, I'll also let you know if it does work. 

Thanks for your help!

**Comment by dzikoysk** [comment]
Sure, I'll merge the PR then, so it'll be available in snapshot builds:)
