### ISSUE TITLE
Snapshot builds don't have updated version in the internals

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/reposilite#1330]
### What happened?

New release properly publish next version:

* https://maven.reposilite.com/#/snapshots/org/panda-lang/reposilite/3.0.0-alpha.26-SNAPSHOT

But the version in sources is not updated, would be great to have it fixed if possible. Probably this hook is not invoked for standard publish build:

https://github.com/dzikoysk/reposilite/blob/08c9a3fe3d85909bbb3727ca8dbf06d124538d69/build.gradle.kts#L41-L52

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
@WithoutAName25 could you take a look on this? :)

**Comment by WithoutAName25** [comment]
These hooks are primarily to update for example the latest version in `README.md` on each full release (not snapshots). With this plugin there is no option to update some versions also for snapshots but I will try to find another solution for that.

**Comment by WithoutAName25** [comment]
My first idea was to include the version in `META-INF/MANIFEST.MF` and then load it during runtime. But because the version is used in annotations, it has to be a compile time constant. [This](https://stackoverflow.com/questions/59692381/how-can-i-modify-java-source-code-in-my-gradle-project-prior-to-compilation-with/59692997#59692997) could work but it's maybe to complex for just getting the correct snapshot version at runtime.

**Comment by dzikoysk** [comment]
So it won't work using axios plugin even if we'd create like a "fake" commit on CI with a next snapshot provided as the next release?

Speaking of the annotations, we can always replace the explicit version with a placeholder resolved during loading, so I think it wouldn't be a problem.

**Comment by WithoutAName25** [comment]
It is not possible with axios plugin, even with "fake" commits. But if we don't need the version at compile time (no annotations with the version), I think the best approach is using `META-INF/MANIFEST.MF`

**Comment by dzikoysk** [comment]
Ok, I think it's worth to give such approach a chance, I even prefer to have sources without explicit references to the current version.

**Comment by WithoutAName25** [comment]
I think we need another solution because `VERSION` is used in some annotations were it's needed:
https://github.com/dzikoysk/reposilite/blob/08c9a3fe3d85909bbb3727ca8dbf06d124538d69/reposilite-backend/src/main/kotlin/com/reposilite/console/CommandExecutor.kt#L32-L33
https://github.com/dzikoysk/reposilite/blob/2811d1f767fb0d1df2328abd28d5d9c70e2be225/reposilite-backend/src/main/kotlin/com/reposilite/plugin/api/Plugin.java#L28-L48
Especially for the plugin api, I think it's better if this is done at compile time, otherwise the default version would be the version of Reposilite that the plugin was loaded with, not the version it was compiled with.
I'm going to try the approach from [StackOverflow](https://stackoverflow.com/questions/59692381/how-can-i-modify-java-source-code-in-my-gradle-project-prior-to-compilation-with/59692997#59692997).
