### ISSUE TITLE
Mangled depencies

### ISSUE THREAD

**Issue by a1730** [dzikoysk/reposilite#1333]
### What happened?

Running 25th pre-release of Reposilite 3.x. 
Reposilite is unable to correctly proxy the following artifact [beautiful_logger](https://github.com/forax/beautiful_logger) from
> <repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>

><dependency>
    <groupId>com.github.forax</groupId>
    <artifactId>beautiful_logger</artifactId>
    <version>master-SNAPSHOT</version>
</dependency>

Gradle reported errors, and the build failed. So, I modified the dependency to
> <dependency>
    <groupId>com.github.forax</groupId>
    <artifactId>beautiful_logger</artifactId>
    <version>0.9.11</version>
</dependency>

Reposilite was able to grab the artifact. Yay! The build worked, but Reposilite UI proposes the following artifact details
> <dependency>
    <groupId>com.github.forax.beautiful_logger</groupId>
    <artifactId>0.9.11</artifactId>
    <version>0.9.11</version>
</dependency>

This is practically wrong
![2022-05-21_154046](https://user-images.githubusercontent.com/1192408/169666809-bdb14326-036d-4a3a-a0f2-c67455c0e577.jpg)
.

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
As far as I see, the problem with the `master-SNAPSHOT` is caused by the error in build phase:

> ![obraz](https://user-images.githubusercontent.com/4235722/169667242-e6a98c7a-3d12-4b52-83ad-ecc922f55157.png)
> ![obraz](https://user-images.githubusercontent.com/4235722/169667239-33bf2493-1240-487c-8e68-369054c25d18.png)
> 
> ~ https://jitpack.io/com/github/forax/beautiful_logger/master-0.9.11-g43e7522-7/build.log

🤔

**Comment by a1730** [comment]
Thank you for the quick response about the build failure.
I was only reporting it for you information.

Did you have a chance to loook at the dependency re-write issue?

>\<groupId>com.github.forax.beautiful_logger\</groupId>
\<artifactId>0.9.11\</artifactId>
\<version>0.9.11\</version>
\</groupId>

The groupId and artifactId are incorrect.
Thank you.

**Comment by dzikoysk** [comment]
Are you sure it's not caused by some kind of a mess from corrupted JitPack build? `/releases/com/github/forax/beautiful_logger` looks fine for me:

![obraz](https://user-images.githubusercontent.com/4235722/169704577-7bf26ea8-6d6b-4fe5-8c58-dfd5688c9882.png)

With this configuration:

![obraz](https://user-images.githubusercontent.com/4235722/169704620-f1d40747-b624-467f-978a-c5133f5972cc.png)

**Comment by dzikoysk** [comment]
Ok, I think I know what could happen. That's in fact a problem with JitPack that generated invalid metadata file:

* https://jitpack.io/com/github/forax/beautiful_logger/0.9.11/maven-metadata.xml

You've probably requested this and Reposilite cached this file and that's why you see misleading artifact details.

**Comment by a1730** [comment]
I see ... Jitpack is a good idea ... Thank you for soending the time to investigate this issue.
Thank you for Reposilite.
