### ISSUE TITLE
Wrong artifact is being downloaded

### ISSUE THREAD

**Issue by jaqobb** [dzikoysk/reposilite#156]
This might be an issue not even related to Reposilite but I don't really know what else may cause this, but:

I uploaded an artifact with the version 1.0.0. I later decided to reupload pretty much the same artifact but with small changes and I decided to leave the version the same (1.0.0). Currently no matter what I do the previous version is being downloaded. While I can easily download the correct artifact from the VPS, trying to download the artifact using the frontend will result in the wrong one being downloaded (even though the frontend shows the correct file size etc.).

Is there something in Reposilite that may be causing this?

For now I tried completely removing the artifact and uploading it one more time. I also tried rebooting Reposilite with hopes that cache will be cleared (if cache was indeed the issue).

**Comment by dzikoysk** [comment]
Do you use some kind of CDN service like Cloudflare?

**Comment by jaqobb** [comment]
Yes, I do. I assume Cloudflare's caching might be responsible for this?

**Comment by dzikoysk** [comment]
It is a problem with cache, because Reposilite does not store any files in memory to reduce usage of resources. You should probably take a look at cf cache policy. I recommend to use custom page rule:

![image](https://user-images.githubusercontent.com/4235722/87345614-9cfb6c80-c550-11ea-83f1-c2521371eeac.png)

Iit might be a good idea to mention it in docs.

**Comment by jaqobb** [comment]
Yeah, this seems to have fixed the issue. Thanks for the quick response. I believe this can be closed now.
