### ISSUE TITLE
Ability to remove /#/ from the vue router

### ISSUE THREAD

**Issue by MichaelHillcox** [dzikoysk/reposilite#1658]
### Request details

I couldn't see this recommended anywhere, but VueJS supports removing the `/#/` in the routes base through the main.js/ts (IIRC). It'd be nice to configure this as with the correct nginx / other setup, you can just route everything to the frontend. This is especially true with docker and reverse proxies.

**Comment by dzikoysk** [comment]
Reposilite 2.x had custom routing implementation on backend that supported such routes, but I've decided to remove it from 3.x. There were 2 main reasons behind that change:

1. We had to mount application in each non-Maven response, because such approach requires to mix both Maven & UI path collision resolution as both of them are served on the same path. It was inconvenient and often resulted in strange coverage of error paths. 
2. Reposilite 3.x is way more flexible, you can not only implement your own custom pages (if for some reason you don't want to expose UI to your Maven instance) + there's plugin API that allows you, for instance, register new routes. 

As a cost of cosmetic disadvantage of having `/#/` in path, in general I see this as pretty healthy change.

**Comment by MichaelHillcox** [comment]
I think that's fair. Seems like a fair trade-off, can't agree that I like the /#/ there, but I'll live. xD

**Comment by dzikoysk** [comment]
Yeah, maybe in 4.x I'll figure out something better :P
