### ISSUE TITLE
Settings tab is empty

### ISSUE THREAD

**Issue by d1snin** [dzikoysk/reposilite#1718]
### What happened?

First time using Reposilite on my server.

I'm running into an issue with settings. The settings tab simply appears to be absolutely empty. Thus, I can't configure my instance the traditional way

![image](https://user-images.githubusercontent.com/68169685/216122826-e64edf73-79c0-4b95-b8aa-2b872c3fdb6f.png)

The dashboard says there are 0 failures.

Using `nightly` build via Docker (`3.2.8-SNAPSHOT`).

Attached browser console output (I don't find it helpful tho).

### Reposilite version

3.x

### Relevant log output

```shell
SyntaxError: illegal character U+FFFD index-f3718608.js:1:15032
    $d https://maven.redacted.com/assets/index-f3718608.js:1
    Un https://maven.redacted.com/assets/index-f3718608.js:1
```

**Comment by d1snin** [comment]
Now running Reposilite `3.2.7`. The settings tab is being rendered fine on that version

**Comment by dzikoysk** [comment]
Looks like an issue with encoding:

* https://unicode-table.com/pl/FFFD/

I'm not quite sure what could be the cause, I'll release 3.3.0 and if this will happen again we'll try to diagnose it.

**Comment by dzikoysk** [comment]
Hmm I can confirm it occurs on `main` now, I guess it was introduced in one of the recent commits.

**Comment by dzikoysk** [comment]
It was a little bit tricky, because it throws at `index-f3718608.js:1` while the issue was located in `SettingsView-b1f65041.js`. It looks like this file contains several long UTF-8 symbols and some of them are not properly buffered by our placeholder resolver (LazyPlaceholderResolver). I've covered this with regular `write` to fallback, so it should work properly in 3.3.0.

**Comment by d1snin** [comment]
TYSM for the fix!
