### ISSUE TITLE
Group and Proxy Repositories

### ISSUE THREAD

**Issue by bo0ts** [dzikoysk/reposilite#1816]
### Request details

While migrating from Nexus 3 to Reposilite I really missed the "Group" and - to a lesser extent - "Proxy" repositories. Although I can emulate those repository types (groups by proxying multiple repositories via localhost, proxies by having only read and a single proxied repository) it would be nice to have those special repository type in reposilite. It would make the UI much cleaner and show the intended purpose of the repository much better.

**Comment by bo0ts** [comment]
After some testing this morning I believe that having dedicated repository types could also improve performance significantly by avoiding unnecessary lookups.

**Comment by dzikoysk** [comment]
> proxying multiple repositories via localhost

You don't have to link local repos through url, you can simply use repository name in link field:

![obraz](https://user-images.githubusercontent.com/4235722/236287482-f68c62a9-d219-450e-aa31-bc701ce51726.png)

>  it would be nice to have those special repository type in reposilite. It would make the UI much cleaner and show the intended purpose of the repository much better

I agree, but current approach is the most flexible one, because you can also mix local repos with mirrored ones if needed. It's also easier to maintain & manage + atm it'd be a breaking change if we'd like to modify this structure.

> After some testing this morning I believe that having dedicated repository types could also improve performance significantly by avoiding unnecessary lookups.

If caching is enabled, this lookup is still needed.
