### ISSUE TITLE
Being able to navigate through the ui with read permissions

### ISSUE THREAD

**Issue by micartey** [dzikoysk/reposilite#1846]
## Request details

When I create a user and add read permissions to a repository, I can download the files as expected **BUT** when using the ui I can't navigate the path.

### Expected Behavior

Being able to navigate the ui when being logged in and having read permission

**Comment by SirEndii** [comment]
Going to add a comment to this, however, I'm not sure how related it is to this issue

So the thing is, I have a user/token setup for a team member of mine in the repository. He has read/write permissions for one repository. So the thing is that he can upload and read just fine, but he can only read via the UI and not write or delete

**Comment by JWood48** [comment]
Would really like this feature! 

Otherwise I have to give manager rights to the other developers if they want to browse the repo

**Comment by rdehuyss** [comment]
Same here. @dzikoysk: what would it cost to have this feature developed?

**Comment by dzikoysk** [comment]
Initially, it wasn't requested by sponsors & I'm starting a new job on Wednesday (so I was lately more involved into interviews & one of my private projects), so it had a lower priority. 

I'll try to check the impl to see what kind of enhancement is required by this change and I'll let you all know. I'm also thinking about a full frontend rewrite, because writing this in Vue 3.0.0 had a lot of drawbacks and led to a significant tech debt, so I'm kinda careful with investing my time in the frontend module.

**Comment by dzikoysk** [comment]
Ok, it should work as requested in the next release (you can also already use it via nightly build). Visible directories are emulated purely on client-side from routes assigned to currently used token. 

API will still return 403 status code for directories, because we don't want to change the existing behavior and affect people that relies on this at some point.

**Comment by rdehuyss** [comment]
First of all, thanks for the quick fix! Second of all, congratz with your new job!

One more question: is it hard to also allow this on API level? If I have a Nexus which proxies reposilite, they can not browse the remote storage. See the attached screenshot:

![image](https://github.com/dzikoysk/reposilite/assets/567842/e2a3583a-1688-4a1c-9661-dde636c084b6)

**Comment by dzikoysk** [comment]
Oh, it's unrelated to the API I've mentioned above - I was talking about a unique to Reposilite set of /api endpoints. Speaking about Nexus:

> When browsing a remote repository you might notice that the tree doesn’t contain all of the components in a repository. When you browse a proxy repository, the repository manager is displaying the components that have been cached locally from the remote repository. If you don’t see an component you expected to see in the repository manager, it only means that it has yet to cache the component locally.

~ https://help.sonatype.com/repomanager2/using-the-user-interface/browsing-repositories

Later on, they mentioned an option to use repository index, but it's kinda unique feature of Nexus (#601) that we don't really support (if that's what they've meant by referencing the index). You could probably try to run Maven Indexer via CLI or try to use:

* https://github.com/solonovamax/reposilite-maven-indexer

But I'm not sure what's the state of this plugin.
