### ISSUE TITLE
Make LDAP objectClass configurable

### ISSUE THREAD

**Issue by cwilhelm** [dzikoysk/reposilite#1879]
### Request details

Can you make objectClass value for authentication configurable too? In our LDAP setup the user a objectClass attribute of **organizationalPerson** or **posixAccount** but not **person**.

`    it.search(
        "(&(objectClass=person)(${userAttribute}=${authenticationRequest.name})${userFilter})", 
    ) `

to

`    it.search(
        "(&(objectClass=${authenticationRequest.objectClass})(${userAttribute}=${authenticationRequest.name})${userFilter})", 
    ) `

**Comment by dzikoysk** [comment]
Yes, we can do that. This implementation was inspired by GitLab and as far as I remember it was hardcoded as `objectClass` 🤔 If you'd like to submit PR just let me know, because I'm currently slightly busy, so I could do that in a few days.

https://github.com/dzikoysk/reposilite/blob/7095c51826b0826ce6a516d2e8f2896da91188c4/reposilite-backend/src/main/kotlin/com/reposilite/auth/LdapAuthenticator.kt#L74-L96

**Comment by dzikoysk** [comment]
It'll be available as `typeAttribute` property in the next release.
