### ISSUE TITLE
Mirror to local repository broken since 3.4.5

### ISSUE THREAD

**Issue by binsentsu** [dzikoysk/reposilite#1929]
### What happened?

Hi,

I have a pretty simple setup of a 'release' repository and a 'dev' repository, both type private. The 'dev' repository mirrors the local release repository by id so all released artifacts should be available through accessing the dev repository. The users' access-token has read right on all repositories (route /)

Now since upgrading to 3.4.5 this setup is not working anymore. The released artifacts in release repository can not be accessed anymore through dev repository. Within version 3.4.4 this still worked. Within the mirror authentication settings nothing was filled in. Repository is accessed through gradle with basic authentication. When directly targeting the release repository everything still works fine as before.

Am I missing some configuration to make this work in 3.4.8?

Thanks

### Reposilite version

3.x

### Relevant log output

```shell
3.4.8 log:

00:41:47.944 DEBUG | HEAD /dev/com/xxx.pom from 172.30.0.9
00:41:47.948 DEBUG |  failed to authenticate with Basic realm due to ErrorResponse(status=401, message=Invalid authorization credentials)
00:41:47.950 DEBUG | ACCESS | Unauthorized attempt of access (token: null) to com/xxx.pom from release
00:41:47.951 DEBUG | FIND | Could not find file due to ErrorResponse(status=404, message=Cannot find 'com/xxx.pom' in local and remote repositories)

3.4.4 log:
00:47:45.294 DEBUG | HEAD /dev/com/xxx.pom from 172.30.0.9
00:47:45.420 DEBUG | Cannot find 'com/xxx.pom' in 'dev' repository, requesting proxied repositories
```

**Comment by dzikoysk** [comment]
3.4.5 replaces the previous primitive local loopback implementation with a new one, that not only supports deeper calls, but also validates permissions in nested repositories. Thanks to that, mirrored local repositories are safer by default, because all requests are limited to the routes & permissions associated with the token, so you can't leak internal data by accident.

To properly configure authentication for mirrored repository, there are 2 ways to do that:
1. If you'd like to share whole repository content to your users (without any auth), you can just simply use `hidden` visibility
2. If you'd like to keep it private, you should generate a new token that has access to the `releases` repository. Then, use this token in mirror credentials section as follows:

![obraz](https://github.com/dzikoysk/reposilite/assets/4235722/5cbd4ae9-0837-4486-94a9-6857aa6b9c11)

**Comment by binsentsu** [comment]
Second mentioned option did the trick. Thanks for the clarification and quick reply!
