### ISSUE TITLE
Odd behavior in the settings menu

### ISSUE THREAD

**Issue by SirEndii** [dzikoysk/reposilite#1980]
### What happened?

When I try to change the storage type of my repository to S3, reposilite asks me if I want to proceed, what I want, but it then deletes all the other options.

See attached video

https://github.com/dzikoysk/reposilite/assets/67484093/4c9049ee-a180-49ec-bb1d-5addc956b9d5

This instance runs on a Kubernetes cluster using the reposilite chart 1.3.0

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Sadly, it's an issue directly related to the library we use to generate these forms from a json scheme:

* https://github.com/dzikoysk/reposilite/issues/1320

I'm afraid that I'm unable to fix that at this moment. Hopefully, we can get rid of it in Reposilite 4.x (or at least a new frontend impl). I'll close it, because it's already linked with the root issue + that's something I can't really change in the current state of the impl :/
