### ISSUE TITLE
Configuration reference

### ISSUE THREAD

**Issue by BeyerByte** [dzikoysk/reposilite#2075]
Referring to Your chapter [Local configuration](https://reposilite.com/guide/general#local-configuration). 
I'm looking for an in depth view of available configuration parameters, e.g. howto setup Proxy for mirroring external repositories.

In reference to [Issue #1797](https://github.com/dzikoysk/reposilite/issues/1797) I was trying to guess the link, but none of them worked.

- [https://reposilite.com/guide/configuration#parameters](https://reposilite.com/guide/configuration#parameters)
- [https://reposilite.com/guide/settings](https://reposilite.com/guide/settings)

Do you have such a configuration parameter List for your configuration.cdn file available?
If not, would it be possible to provide such a file linked at your page? 
I guess that would make ramp up time of your awesome project more efficient.

Thanks a lot.

**Comment by dzikoysk** [comment]
Hey, so the local configuration contains only properties that have been listed in your first link:

* https://reposilite.com/guide/general#local-configuration

You can't set mirrors (proxy) here, because these settings are a part of shared configuration. By default, shared configuration is stored in the database and can be modified in UI using management token:

*https://reposilite.com/guide/dashboard#shared-configuration

If this is absolutely needed for some edge cases, this is also possible to mount shared configuration as a file:

https://reposilite.com/guide/general#shared-configuration-as-file

The full mirror config is not in this snippet (`proxied: []`), but it'd look like this:

```json
"proxied": [
{
  "reference": "https://repo.maven.apache.org/maven2",
  "store": false,
  "allowedGroups": [],
  "allowedExtensions": [
    ".jar",
    ".war",
    ".pom",
    ".xml",
    ".md5",
    ".sha1",
    ".sha256",
    ".sha512",
    ".asc",
    ".module"
  ],
  "connectTimeout": 3,
  "readTimeout": 15,
  "httpProxy": ""
}
```

I hope it helps, maybe I could help even more if I'd know the full context.

**Comment by BeyerByte** [comment]
That helps a lot.
Thank you very much @dzikoysk !
