### ISSUE TITLE
Misreported `content-length` headers with `compressionStrategy=gzip`

### ISSUE THREAD

**Issue by diareuse** [dzikoysk/reposilite#2134]
### Current behavior

HEAD for a file when `compressionStrategy=none` reports:
 - `content-length: <actual file size>`

HEAD for a file when `compressionStrategy=gzip` reports:
 - `content-length: 0`

### Expected result

HEAD for a file when `compressionStrategy=none` reports:
 - `content-length: <actual file size>`

HEAD for a file when `compressionStrategy=gzip` reports:
 - `content-length: <actual file size>`

---

I believe that content-length should report real file size even though `compressionStrategy` is set to `gzip` as HEAD request doesn't necessarily need to know about `gzip` compression to report the file size. GET _can_ report `content-length: 0`, as if it would strongly adhere to the wording in the docs, it would've needed to report gzipped size, which is - as far as I'm aware - impossible to calculate without saving intermediary gzipped file.

Moreover, when requesting file size via HEAD, clients might want to pre-allocate space so calculating "gzipped" length is kind of unwanted anyway.

[Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length) are vague at best on this matter, but I think it can be understood both ways…

---

Let me know what you think

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Unfortunately we can't put the uncompressed file size in this header, because clients that relay on this value would get incorrect assumption on how many bytes it should read. 

The content length header represents number of bytes in the message body - it means it's referring to the already compressed data. The decompression is done after downloading the message body, so we have to treat it as a standalone step (which might be optional, because you could just store gzipped data to save some space).

**Comment by diareuse** [comment]
That's a valid point that I tried to - incoherently - express as a case for the GET method.

I don't necessarily believe it's the same case for the HEAD method though. HEAD doesn't respect the `accept-encoding` header (which I think is totally fine) therefore it should show the _actual_ size of the file(?), if that makes any sense.

---

I totally understand the decision made here haha, would've made the same one.

**Comment by dzikoysk** [comment]
I think that in general, you should never relay on HEAD requests for this kind of information. The reason for that is quite simple - making 2 HTTP requests is not the atomic operation, so state of the file can change between them anyway (for instance I can reupload file with different content). 

I'm also a bit sceptical about modyfing that part, because in the past we had a few issues with these requests. There're so many different Maven implementations and HTTP clients used under the hood (like literally based on 20 years old HTTP/1.0 libs) that this is quite fragile behavior. Current approach seems to work great so far, so it seems to cover all we actually need. 

If for some reason you need that information, I'd personally recommend disabling the compression - in most cases it simply doesn't matter, but you'd get what you want.

**Comment by diareuse** [comment]
Touché, I won't push you too hard on this as I wouldn't want to break people's instances either.

I was only wondering whether there's a such possibility since I'm hosting very very large files which _do_ benefit hugely from compression over the network _and_ I care more about bandwidth than runtime performance as it specifically is not an issue. I do thank you for your consideration and quick response though 🫡 

I may circumvent this by hosting the artifacts as straight up zips, but I'll lose the decompressed size information that way… _Man can't have it all_ haha.

Cheers, and thanks again!
