### ISSUE TITLE
Authorizations per token

### ISSUE THREAD

**Issue by utarwyn** [dzikoysk/reposilite#233]
Actual context
---
As I am using your project for a growing project, I would like to give the deploy permission only to a list of personal tokens. For now a personal token can access and deploy associated artifacts/groups and there is no way to separate these permissions.

Implementation I would do
---
I was thinking about a permission list in the Token object: one for retrieving items, one for deploying, etc. You will be able to add more permissions in the future. For backward compatibility, every personal token created before get all permissions.

**Comment by dzikoysk** [comment]
Summing up our conversation on twitter, at this moment we have to variants of possible implementation:
* cover this feature with some kind of prefix (simple)
* reimplementation of token structure, also requires migrator (future-oriented)

At first, I thought the first one might be a better choice for now, but... the more that I thought about it afterward, the more I'm inclined to the second variant. 

A new token structure should:
* Use CDN instead of YAML (better mappings, easier to update entity structure in the future)
* As you said, token should also contain list of permission names like `"deploy"`, `"access"`.
* Manager flag might be converted into `"manager"` permission
* Support previous configuration

Such an update will also require update of frontend module to accept and respect these values.

**Comment by dzikoysk** [comment]
I think, I've figured it out. List of current permissions:

* `r` - read
* `w` - write (deploy)
* `m` - manager
* some new permissions may be supported in the future

To declare them we need to just add a suffix in a unix-like format, e.g. `*wildcard-readonly:r`. By default every token has `rw` rights.

**Comment by utarwyn** [comment]
Awesome idea 👌
