### ISSUE TITLE
Support distribution in WAR format

### ISSUE THREAD

**Issue by srbala** [dzikoysk/reposilite#304]
This is more of a question. Is it possible run the project WAR file and run port of a web container TomEE or JBossAS

**Comment by dzikoysk** [comment]
Reposilite uses Javalin framework which is implemented on top of the Jetty server. There is an option to use [Servlet Container](https://javalin.io/2018/11/15/javalin-embedded-example.html), but it would require some work around the reimplementation of current web server. 

May I ask why do you think it is important in your case to move away from Jetty?

**Comment by srbala** [comment]
I have already have java server, maven repository to be part of that stack, instead of running as separate instance.

**Comment by dzikoysk** [comment]
I've marked it as a feature request, but I don't think I'll be able to support this in the near future, because it's not really must-have factor. To support WAR format I'd be probably forced to create and maintain a new module `reposilite-servlet` to build such a deployment archives :<

Let's wait for more feedback addressing this issue.

**Comment by srbala** [comment]
if you could give some pointers, myself or community can give some help
