### ISSUE TITLE
Can access CLI but no commands get sent

### ISSUE THREAD

**Issue by schiasileon** [dzikoysk/reposilite#328]
Running version 2.9.8 on a server (no docker), generated admin token at /, defined admin as manager in config, restarted.
I am able to access CLI with admin user, console responses with "CLI admin accessed CLI from /[IP]", but if I try to type any 
commands, none of them get sent. No errors in log (with debug enabled), browser shows error below. Tested on both Chrome and Edge.

![image](https://user-images.githubusercontent.com/32979435/103490549-dc7a8580-4e1c-11eb-8612-429db1dda402.png)

**Comment by dzikoysk** [comment]
To be honest, managers from configuration file are deprecated. Could you generate a token with `m` permission?

**Comment by schiasileon** [comment]
> To be honest, managers from configuration file are deprecated. Could you generate a token with `m` permission?

admin was created with m permission AND is noted under managers, tried without manager in config too

**Comment by dzikoysk** [comment]
Thanks for reporting this :) Could you provide me the rest of your configuration? It's late where I live, so I'll take a look at this tomorrow. I've changed the command system in the latest update, and it looks like something went wrong 😳

**Comment by schiasileon** [comment]
I emailed you all included files.

**Comment by dzikoysk** [comment]
Well, I've played with it for a while and overall I didn't experience an authorization issue caused by any sort of bug in Reposilite. The only 401 error message was caused by invalid credentials and during serving Reposilite through nginx on custom base path (it's kinda bugged now, but you're not using this option).

Could you try with 2.9.9: [reposilite-2.9.9.zip](https://github.com/dzikoysk/reposilite/files/5764956/reposilite-2.9.9.zip) (rename it from zip to jar - GitHub does not allow to upload jar files)

**Comment by schiasileon** [comment]
fixed with 2.9.9

**Comment by dzikoysk** [comment]
I'm glad to hear it :) I'm going to fix #296, and I'll publish the official 2.9.9 release.
