### ISSUE TITLE
block searching of proxies for an artifact

### ISSUE THREAD

**Issue by zzmgck** [dzikoysk/reposilite#406]
I could not find this in the documentation, so hopefully I did not miss something.  I want to block the searching of proxies for certain artifacts if they are not found in the repository.  Ideally it would be great if a wildcard or regex could be specified.  The goal would be to prevent searching for artifacts that are not public (or if there is a private version of a public artifact).

**Comment by dzikoysk** [comment]
Hi there :) There is no such a possibility atm, but it's quite an interesting problem. It looks like a security related issue due to a possibility of leaking some private information. When I think about various scenarios related to this issue, it looks like we should disable proxying through private repositories at all.

**Comment by dzikoysk** [comment]
~ https://github.com/dzikoysk/reposilite/releases/tag/2.9.19

**Comment by zzmgck** [comment]
Wow--that was fast.  There is definitely a security aspect to think about (https://www.schneier.com/blog/archives/2021/02/dependency-confusion-another-supply-chain-vulnerability.html). Thanks!
