### ISSUE TITLE
Purging old versions before

### ISSUE THREAD

**Issue by milkyway0308** [dzikoysk/reposilite#474]
Hello, long time to see you.
Cause reposilite not supporting plug-ins, or addons, I think reposilite need purging version.
Can I request purging command with reposilite?

ex) 
  versionpurge [until/only] [groupId:artifactId:version]
    Purge old version of artifacts.

**Comment by dzikoysk** [comment]
Hi :)

We already have an issue related to this topic #385. Because of the various issues and PRs associated with the new breaking release of Reposilite 3.0, it's kinda impossible for me to implement this feature until it happen. 

If you have some suggestions on how we should purge old artifacts, just continue in #385.
