### ISSUE TITLE
Support ~ operator in GAV

### ISSUE THREAD

**Issue by rdmchr** [dzikoysk/reposilite#504]
I'm having trouble fetching an artifact. When I try to pull it using IntelliJ I get this error message:
`Could not transfer artifact com.github.DV8FromTheWorld:JDA:pom:feature~slash-commands-v3.7.1-g05d58f1-789 from/to radmacher (<URL>): Transfer failed for <URL>/com/github/DV8FromTheWorld/JDA/feature~slash-commands-v3.7.1-g05d58f1-789/JDA-feature~slash-commands-v3.7.1-g05d58f1-789.pom 400 Bad Request`
The artifact is available on [Jitpack.io](https://jitpack.io/#DV8FromTheWorld/JDA/feature~slash-commands-v3.7.1-g05d58f1-789), but I can not fetch it using my reposilite instance.
When I try to click the link to open the artifact in my browser I see an `Invalid GAV path` error.

I already made sure that Jitpack is listed as a remote repository in my reposilite instance, so I'm guessing that reposilite just thinks that the artifact has an invalid name.

**Comment by dzikoysk** [comment]
Hi there :)

Yes, the request file contains invalid character: `~`. As you can see here:

* https://github.com/dzikoysk/reposilite/blob/2db39c354aac290fc6bcef285e5a0c39196bc189/reposilite-backend/src/main/java/org/panda_lang/reposilite/ReposiliteUtils.java#L46

It's illegal, because it's one of the special path characters that could violate security policy in some cases.  As far as I remember Maven declares these pattern `[A-Za-z0-9_\\-.]+` as a valid GAV name. Looking through the stackoverflow I see, that Gradle may allow you to push artifacts with `~`, but still - I don't really recommend.

**Comment by rdmchr** [comment]
Hey

I'm not too familiar with Jitpack, but Jitpack replaces `/` with `*` if I'm reading [this](https://github.com/DV8FromTheWorld/JDA/wiki/10%29-FAQ#how-do-i-test-other-builds) right. This means that builds from branches with the name `feature/thing`, for example, wouldn't be available through reposilite. Is there any way this can be changed?

**Comment by dzikoysk** [comment]
I see:

![image](https://user-images.githubusercontent.com/4235722/120566345-584e1d80-c40f-11eb-8333-223b073d8c23.png)

This is so strange tbh. As a workaround you can just clone Reposilite and replace `uri.contains("~")` with some kind of a pattern that excludes paths with `~` that have some text around it and then I think it may work for you. I'll try to also verify this case in Reposlite 3.x development and we will see if it is safe to support. 

May I ask why do you need to proxy Jitpack, are you looking for repository + CI out of the box? 🤔

**Comment by rdmchr** [comment]
No, it's more of a luxury thing. Using my own repository allows me to not rely on another host which might be offline. But most importantly I can just have one repository in all my pom.xml files. I also use some custom libraries that are only on my repository, so I would need one anyway.
