### ISSUE TITLE
Migrating from Nexus to Reposilite

### ISSUE THREAD

**Issue by PiggyPiglet** [dzikoysk/reposilite#522]
Is there any easy way to do this? Would like to replace nexus on my personal VPS with reposilite to clear up some resources for other projects, but as people already depend on my repository, I need to be able to cleanly transfer everything over.

Nexus version: OSS 3.17.0-01
OS: Ubuntu 16.04.7 LTS

**Comment by dzikoysk** [comment]
Hi there :) 

At this moment it might be difficult, because you're probably using something like `content/repositories` in Nexus. Of course, you could try to rewrite paths using some kind of proxy service like Nginx. Moving repository data should be an easier task, as you only need to move its content to the Reposilite's directory.

**Comment by PiggyPiglet** [comment]
Thanks for the help, got it set up. If anyone is interested, I used this tool to generate a format from nexus that reposilite could read: https://github.com/lbar/nexus3-export. From there, it's as simple as copying the files over like dzikoysk said.

**Comment by dzikoysk** [comment]
I'll keep this open as it might be a good idea to mention it in e.g. FAQ section on the website. I'll try to add this as soon as the 3.0 branch will be merged.
