### ISSUE TITLE
Proxy store whitelist

### ISSUE THREAD

**Issue by AlessioDP** [dzikoysk/reposilite#556]
I would like to have a whitelist (per-package/per-root-package) to only allow some specific proxied artifacts.

For example:
```
proxyWhitelist: [
  "a.simple.package.*" // Any artifact that starts with "a.simple.package"
  "this.specific.package"
]
```

So I can whitelist the packages that I want and prevent other users to use my repository to cache them all.

**Comment by dzikoysk** [comment]
Rather than the dedicated property in configuration, we could move it to the proxied host configuration used in Reposilite 3.x:

* https://github.com/dzikoysk/reposilite/blob/adcc34110f2c0d86be594e6bbea73c825615d8a4/reposilite-backend/src/main/kotlin/com/reposilite/config/Configuration.kt#L143

To provide multiple patterns, user should provide multiple flags:

```
proxied [
    https://repo.panda-lang.org --store --whitelist "a.b.c" --whitelist "x.y.z",
]
```

I think it should support by default packages that starts with such a pattern. It's easier to implement and it would be probably the most common usage of this feature anyway.
