### ISSUE TITLE
Private repositories are not shown automatically after login

### ISSUE THREAD

**Issue by WithoutAName25** [dzikoysk/reposilite#911]
### What happened?

If you log in with your access token the overview tab of `Index of /` is not resynced that causes that private repositories are only shown if you reload the whole page. The same happens if you logout. So if you logout the private repositories are still visible until you reload the website.

### Reposilite version

3.x

**Comment by dzikoysk** [comment]
Thanks, I missed it. Probably because of this change:

* https://github.com/dzikoysk/reposilite/blob/19a5f611d7395c41cc9d67c3027c903418b434e1/reposilite-frontend/src/components/browser/Browser.vue#L106

We should use dedicated client per watch call as it was before. Do you want to try to fix this? :)
